// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoStartEnabled() {
  return window['go']['main']['App']['AutoStartEnabled']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateShortcut() {
  return window['go']['main']['App']['CreateShortcut']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetSystemStats() {
  return window['go']['main']['App']['GetSystemStats']();
}

export function GoToPage(arg1) {
  return window['go']['main']['App']['GoToPage'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SetAutoStartEnabled(arg1) {
  return window['go']['main']['App']['SetAutoStartEnabled'](arg1);
}

export function SetBacklight(arg1) {
  return window['go']['main']['App']['SetBacklight'](arg1);
}

export function SetDateTime() {
  return window['go']['main']['App']['SetDateTime']();
}

export function SetNotes(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetNotes'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetPage(arg1) {
  return window['go']['main']['App']['SetPage'](arg1);
}

export function SetSystemDateTime(arg1) {
  return window['go']['main']['App']['SetSystemDateTime'](arg1);
}

export function StartMonitor(arg1) {
  return window['go']['main']['App']['StartMonitor'](arg1);
}

export function StopMonitor() {
  return window['go']['main']['App']['StopMonitor']();
}

export function WriteText(arg1, arg2) {
  return window['go']['main']['App']['WriteText'](arg1, arg2);
}
