// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutoStartEnabled():Promise<boolean>;

export function Connect(arg1:string):Promise<void>;

export function CreateShortcut():Promise<string>;

export function Disconnect():Promise<void>;

export function GetNotes():Promise<Array<any>>;

export function GetSchedules():Promise<Array<main.scheduleRule>>;

export function GetSystemStats():Promise<Record<string, any>>;

export function GetWeatherConfig():Promise<Record<string, any>>;

export function GoToPage(arg1:number):Promise<void>;

export function IsConnected():Promise<boolean>;

export function RestoreTheme():Promise<void>;

export function RestoreThemeFromPath(arg1:string):Promise<void>;

export function SetAutoStartEnabled(arg1:boolean):Promise<void>;

export function SetBacklight(arg1:number):Promise<void>;

export function SetDateTime():Promise<void>;

export function SetNotes(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SetPage(arg1:number):Promise<void>;

export function SetSchedules(arg1:Array<main.scheduleRule>):Promise<void>;

export function SetSystemDateTime(arg1:string):Promise<void>;

export function SetWeatherConfig(arg1:string):Promise<void>;

export function StartMonitor(arg1:number):Promise<void>;

export function StopMonitor():Promise<void>;

export function UploadGifFile(arg1:Array<number>):Promise<void>;

export function UploadGifFromPath(arg1:string):Promise<void>;

export function UploadImageToTheme(arg1:Array<number>,arg2:number):Promise<void>;

export function WriteText(arg1:string,arg2:number):Promise<void>;
